### ISSUE TITLE
auro-icon: add oneworld lockups

### ISSUE THREAD

**Issue by sryckman** [AlaskaAirlines/auro-lockup#5]
## What is the requested web component?

We have two new Alaska oneworld lockups to add for design and dev use cases

## Features

> Please list out the features of the proposed web component

1. Official lockup
2. Contextual lockup

## Is there any prior art related to this proposal?

- [x] YES
- [ ] NO

### Prior art

> If YES to the question above, please list all URLs to prior art and/or attach screen shots for review.

## Agreement

By checking the box below I acknowledge that the proposed web component does not duplicate any existing feature or functionality within the Auro Design System. The proposal is requesting support for a feature that is currently not supported.

- [x] I certify that this proposal does not replicate any existing design or functionality.
## Additional context

> Please list any other additional information you see necessary to communicate the scope of the proposed web component.

[Alaska oneworld contextual and official.zip](https://github.com/AlaskaAirlines/auro-icon/files/6025079/Alaska.oneworld.contextual.and.official.zip)

**Comment by blackfalcon** [comment]
@jason-capsule42 the work scope here is to use the attached comp as a guide to update the auro-lockup and add a new `oneworld` feature that would replace the PRODUCT NAME and POWERED BY... headers. 

A secondary feature is to allow for a switch between the Alaska Airlines Official logo as currently installed and replace that with the standard Alaska logo, [see](https://auro.alaskaair.com/components/auro/icon/alaska).

**Comment by jason-capsule42** [comment]
@blackfalcon the original SVG for this has a viewBox of "0 0 633 176" - a lot bigger than the other icons like it. Do I need to create versions to match the other tagline size variations or am I just adding the one with the viewBox as originally defined?

**Comment by blackfalcon** [comment]
@jason-capsule42 the work is not to add this to the SVG lib. The work is to update the lockup to match the provided UI. 

The Alaska and Oneworld logos are already part of the Icons lib.

**Comment by jason-capsule42** [comment]
Ah that makes sense. Thanks, @blackfalcon.
